import DashboardLayoutWrapper from "@/components/dashboardComponents/commonDashboardComps/DashboardLayoutWrapper";
import { SearchProvider } from "@/context/SearchContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SearchProvider>
      <DashboardLayoutWrapper>{children}</DashboardLayoutWrapper>
    </SearchProvider>
  );
}
